import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Plus, Upload, X, Fingerprint } from "lucide-react";
import { useAddEmployee, generateEmployeeId } from "@/hooks/useEmployees";
import { useRegisterBiometric } from "@/hooks/useBiometric";
import { Database } from "@/integrations/supabase/types";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { isWebAuthnSupported } from "@/utils/mobileUtils";

type DepartmentType = Database["public"]["Enums"]["department_type"];

const departments: DepartmentType[] = ["Enamel", "Workshop", "Guards", "Cooks", "Admins", "Directors", "Accounts"];

export default function AddEmployeeDialog() {
  const [open, setOpen] = useState(false);
  const [isGeneratingId, setIsGeneratingId] = useState(false);
  const [employeeId, setEmployeeId] = useState("");
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [enableBiometric, setEnableBiometric] = useState(false);
  const [deviceName, setDeviceName] = useState("");
  const [isRegisteringBiometric, setIsRegisteringBiometric] = useState(false);
  const addEmployee = useAddEmployee();
  const registerBiometric = useRegisterBiometric();

  // Generate employee ID when dialog opens
  useEffect(() => {
    if (open && !employeeId) {
      handleGenerateId();
    }
  }, [open]);

  const handleGenerateId = async () => {
    setIsGeneratingId(true);
    try {
      const newId = await generateEmployeeId();
      setEmployeeId(newId);
    } catch (error: any) {
      toast.error("Failed to generate employee ID");
    } finally {
      setIsGeneratingId(false);
    }
  };

  const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        toast.error("Image size must be less than 5MB");
        return;
      }
      setPhotoFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setPhotoPreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const removePhoto = () => {
    setPhotoFile(null);
    setPhotoPreview(null);
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);

    if (!employeeId) {
      toast.error("Please generate an employee ID first");
      return;
    }

    let photoUrl = null;

    // Upload photo if selected
    if (photoFile) {
      const fileExt = photoFile.name.split('.').pop();
      const fileName = `${employeeId}-${Date.now()}.${fileExt}`;
      const { data: uploadData, error: uploadError } = await supabase.storage
        .from('employee-photos')
        .upload(fileName, photoFile);

      if (uploadError) {
        toast.error("Failed to upload photo");
        return;
      }

      const { data: urlData } = supabase.storage
        .from('employee-photos')
        .getPublicUrl(fileName);
      
      photoUrl = urlData.publicUrl;
    }

    // Add employee first
    const newEmployee = await addEmployee.mutateAsync({
      employee_id: employeeId,
      name: formData.get("name") as string,
      cnic: formData.get("cnic") as string,
      department: formData.get("department") as DepartmentType,
      contact: formData.get("contact") as string,
      joining_date: formData.get("joining_date") as string,
      base_salary: Number(formData.get("base_salary")),
      overtime_rate: Number(formData.get("overtime_rate")) || 0,
      overtime_wage: Number(formData.get("overtime_wage")) || 0,
      photo_url: photoUrl,
      biometric_registered: false,
      biometric_credential_id: null,
      biometric_public_key: null,
      biometric_registered_at: null,
      biometric_device_info: null,
    });

    // Register biometric if enabled
    if (enableBiometric && deviceName.trim()) {
      setIsRegisteringBiometric(true);
      try {
        await registerBiometric.mutateAsync({
          employee_id: newEmployee.id,
          device_name: deviceName,
          credential_id: "", // Will be generated by the hook
          public_key: "", // Will be generated by the hook
          device_info: null, // Will be generated by the hook
        });
        toast.success("Employee added and biometric registered successfully!");
      } catch (error: any) {
        toast.error("Employee added but biometric registration failed: " + error.message);
      } finally {
        setIsRegisteringBiometric(false);
      }
    }

    setOpen(false);
    setEmployeeId("");
    setPhotoFile(null);
    setPhotoPreview(null);
    setEnableBiometric(false);
    setDeviceName("");
    (e.target as HTMLFormElement).reset();
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="bg-gradient-primary shadow-medium hover:shadow-strong transition-all">
          <Plus className="mr-2 h-4 w-4" />
          Add Employee
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Add New Employee</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label>Profile Photo</Label>
            <div className="flex items-center gap-4">
              {photoPreview ? (
                <div className="relative">
                  <img 
                    src={photoPreview} 
                    alt="Preview" 
                    className="w-24 h-24 rounded-full object-cover border-2 border-border"
                  />
                  <Button
                    type="button"
                    variant="destructive"
                    size="icon"
                    className="absolute -top-2 -right-2 h-6 w-6 rounded-full"
                    onClick={removePhoto}
                  >
                    <X className="h-3 w-3" />
                  </Button>
                </div>
              ) : (
                <div className="w-24 h-24 rounded-full bg-muted flex items-center justify-center border-2 border-dashed border-border">
                  <Upload className="h-8 w-8 text-muted-foreground" />
                </div>
              )}
              <div className="flex-1">
                <Input
                  type="file"
                  accept="image/*"
                  onChange={handlePhotoChange}
                  className="cursor-pointer"
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Max 5MB (JPG, PNG, WEBP)
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="employee_id">Employee ID</Label>
            <div className="flex gap-2">
              <Input 
                id="employee_id" 
                value={employeeId} 
                placeholder="Click to generate" 
                readOnly 
                required 
              />
              <Button 
                type="button" 
                onClick={handleGenerateId}
                disabled={isGeneratingId}
                variant="outline"
              >
                {isGeneratingId ? "..." : "Generate"}
              </Button>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="name">Full Name</Label>
            <Input id="name" name="name" placeholder="Ahmed Khan" required />
          </div>

          <div className="space-y-2">
            <Label htmlFor="cnic">CNIC</Label>
            <Input id="cnic" name="cnic" placeholder="42101-1234567-1" required />
          </div>

          <div className="space-y-2">
            <Label htmlFor="department">Department</Label>
            <Select name="department" required>
              <SelectTrigger>
                <SelectValue placeholder="Select department" />
              </SelectTrigger>
              <SelectContent>
                {departments.map((dept) => (
                  <SelectItem key={dept} value={dept}>
                    {dept}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="contact">Contact</Label>
            <Input id="contact" name="contact" placeholder="+92-300-1234567" />
          </div>

          <div className="space-y-2">
            <Label htmlFor="joining_date">Joining Date</Label>
            <Input 
              id="joining_date" 
              name="joining_date" 
              type="date" 
              defaultValue={new Date().toISOString().split("T")[0]}
              required 
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="base_salary">Monthly Salary (PKR)</Label>
            <Input id="base_salary" name="base_salary" type="number" placeholder="50000" required />
          </div>

          <div className="space-y-2">
            <Label htmlFor="overtime_wage">Overtime Hourly Wage</Label>
            <Input id="overtime_wage" name="overtime_wage" type="number" placeholder="500" />
            <p className="text-xs text-muted-foreground">Amount paid per overtime hour</p>
          </div>

          {/* Biometric Registration Section */}
          <div className="space-y-4 p-4 border rounded-lg bg-muted/30">
            <div className="flex items-center space-x-2">
              <Checkbox 
                id="enable_biometric" 
                checked={enableBiometric}
                onCheckedChange={(checked) => setEnableBiometric(checked as boolean)}
              />
              <Label htmlFor="enable_biometric" className="flex items-center gap-2">
                <Fingerprint className="h-4 w-4" />
                Enable Biometric Registration
              </Label>
            </div>
            
            {enableBiometric && (
              <div className="space-y-3">
                <div className="space-y-2">
                  <Label htmlFor="device_name">Device Name</Label>
                  <Input 
                    id="device_name" 
                    value={deviceName}
                    onChange={(e) => setDeviceName(e.target.value)}
                    placeholder="e.g., Office Kiosk, My Tablet"
                    required={enableBiometric}
                  />
                  <p className="text-xs text-muted-foreground">
                    Name to identify this biometric device
                  </p>
                </div>
                
                {!isWebAuthnSupported() && (
                  <div className="text-xs text-warning bg-warning/10 p-2 rounded">
                    ⚠️ Biometric authentication is not supported on this device. 
                    Registration will be skipped.
                  </div>
                )}
                
                {isWebAuthnSupported() && (
                  <div className="text-xs text-success bg-success/10 p-2 rounded">
                    ✅ This device supports biometric authentication. 
                    You'll be prompted to scan your fingerprint/face during registration.
                  </div>
                )}
              </div>
            )}
          </div>

          <Button 
            type="submit" 
            className="w-full" 
            disabled={addEmployee.isPending || isRegisteringBiometric}
          >
            {addEmployee.isPending || isRegisteringBiometric 
              ? (isRegisteringBiometric ? "Registering Biometric..." : "Adding...") 
              : "Add Employee"
            }
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}
